#!/usr/bin/env node
/* eslint-disable */
const fsExtra = require('fs-extra');
const { execSync } = require('child_process');

function generateViteReactApp(appName) {
  const appPath = `./${appName}`;

  // Create the app directory
  fsExtra.ensureDirSync(appPath);

  // Copy your custom template structure
  const templatePath = './custom-template';
  fsExtra.copySync(templatePath, appPath);

  // Run the Vite create command
  execSync(`npx create-vite ${appName} --template react`, { stdio: 'inherit' });

  console.log(`Vite React app '${appName}' created successfully!`);
}

// Read the app name from the command line arguments
const appName = process.argv[2];

if (!appName) {
  console.error('Please provide an app name: npx vite-reactjs <appName>');
  process.exit(1);
}

generateViteReactApp(appName);
